//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kval
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriendsBaseEntities : DbContext
    {
        private static FriendsBaseEntities context;
        public FriendsBaseEntities()
            : base("name=FriendsBaseEntities")
        {
        }

        public static FriendsBaseEntities GetContext()
        {
            if (context == null)
                context = new FriendsBaseEntities();
            return context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Phones> Phones { get; set; }
        public virtual DbSet<Significant_dates> Significant_dates { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
