//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kval
{
    using System;
    using System.Collections.Generic;
    
    public partial class Significant_dates
    {
        public int id_Date { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_end { get; set; }
        public int id_Friend1 { get; set; }
        public Nullable<int> id_Friend2 { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Friends Friends { get; set; }
    }
}
